### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by Zorbash** [WordPress/browsehappy#4]
I wish there was internationalization, so that i could redirect non english speaking users to browserhappy.com without causing confusion.

I'm willing to provide a greek translation.

**Comment by coffee2code** [comment]
As a belated follow-up: localized translations of the site can be contributed via the GlotPress installation at https://translate.wordpress.org/projects/meta/browsehappy (changed since the link mentioned in the previous comment). Instructions are provided at the link.

As of this moment, there is a Greek translation of the site that is 96% complete (only 1 string is untranslated).
