### ISSUE TITLE
Support Palemoon

### ISSUE THREAD

**Issue by hkmaly** [WordPress/browsehappy#42]
Hello, can you add Palemoon or at least stop complaining that it's insecure verion of Firefox?

https://www.palemoon.org/

**Comment by coffee2code** [comment]
The Browse Happy API (which is actually a separate [project repository](https://meta.trac.wordpress.org/browser/sites/trunk/api.wordpress.org/public_html/core/browse-happy/), though you can't be faulted for not knowing since there is no mention of it in the README yet) has been [updated](https://meta.trac.wordpress.org/changeset/6012) to recognize Pale Moon as a distinct browser. As such, it should no longer be misreported as an insecure version of Firefox.

Note that the insecure browser nag in WordPress caches the API response from Browse Happy for a week, so it can as much as that much time before a given site re-fetches to obtain an updated (and correct) response.
