### ISSUE TITLE
Incorrect Firefox Version Info On Website But Correct Version Info on Google Search

### ISSUE THREAD

**Issue by possnfiffer** [WordPress/browsehappy#51]
The website https://browsehappy.com shows Firefox as version 9.06!

![browsehappywebsitev9_06](https://user-images.githubusercontent.com/773239/48639357-950cb300-e990-11e8-82bd-c662b3b53b59.png)

Google search results show Firefox as version 63 
![browsehappysearchresultv63](https://user-images.githubusercontent.com/773239/48639358-950cb300-e990-11e8-89e6-4f76e713cf19.png)

**Comment by coffee2code** [comment]
@possnfiffer: Thanks for the report!

I think you might've caught the site at a time when it received erroneous data. It checks WikiData's entry for Firefox and gets the software version identifier for the latest stable version. Being Wiki-based, it's likely someone incorrectly changed something. I didn't delve too deeply at WikiData to verify that was the case, but according to the Web Archive, the [incorrect value started appearing](http://web.archive.org/web/20181116161716/https://browsehappy.com/) the day you reported it (Nov 16th) but then the [correct value was being shown](http://web.archive.org/web/20181117173851/https://browsehappy.com/) by the evening of the next day (Nov 17th).

I did check periodically since your report to see if the problem cropped up again. But other than that hiccup, it seems to have been correct.

Cheers!
